<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Currency;
use Exception;


class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::beginTransaction();
        try
        {
            $currencies = [
                [
                    'name' => 'United Arab Emirates Dirham',
                    'code' => 'AED',
                    'symbol' => 'د.إ',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Afghan Afghani',
                    'code' => 'AFN',
                    'symbol' => '؋',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Albanian Lek',
                    'code' => 'ALL',
                    'symbol' => 'L',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Armenian Dram',
                    'code' => 'AMD',
                    'symbol' => '֏',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Netherlands Antillean Guilder',
                    'code' => 'ANG',
                    'symbol' => 'ƒ',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Angolan Kwanza',
                    'code' => 'AOA',
                    'symbol' => 'Kz',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Argentine Peso',
                    'code' => 'ARS',
                    'symbol' => '$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Australian Dollar',
                    'code' => 'AUD',
                    'symbol' => 'A$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Aruban Florin',
                    'code' => 'AWG',
                    'symbol' => 'ƒ',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Azerbaijani Manat',
                    'code' => 'AZN',
                    'symbol' => '₼',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bosnia-Herzegovina Convertible Mark',
                    'code' => 'BAM',
                    'symbol' => 'KM',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Barbadian Dollar',
                    'code' => 'BBD',
                    'symbol' => 'Bds$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bangladeshi Taka',
                    'code' => 'BDT',
                    'symbol' => '৳',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bulgarian Lev',
                    'code' => 'BGN',
                    'symbol' => 'лв',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bahraini Dinar',
                    'code' => 'BHD',
                    'symbol' => '.د.ب',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Burundian Franc',
                    'code' => 'BIF',
                    'symbol' => 'FBu',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bermudian Dollar',
                    'code' => 'BMD',
                    'symbol' => 'BD$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Brunei Dollar',
                    'code' => 'BND',
                    'symbol' => 'B$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bolivian Boliviano',
                    'code' => 'BOB',
                    'symbol' => 'Bs.',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Brazilian Real',
                    'code' => 'BRL',
                    'symbol' => 'R$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bahamian Dollar',
                    'code' => 'BSD',
                    'symbol' => 'B$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Bhutanese Ngultrum',
                    'code' => 'BTN',
                    'symbol' => 'Nu.',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Botswana Pula',
                    'code' => 'BWP',
                    'symbol' => 'P',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Belarusian Ruble',
                    'code' => 'BYN',
                    'symbol' => 'Br',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Belize Dollar',
                    'code' => 'BZD',
                    'symbol' => 'BZ$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Canadian Dollar',
                    'code' => 'CAD',
                    'symbol' => 'C$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Congolese Franc',
                    'code' => 'CDF',
                    'symbol' => 'FC',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Swiss Franc',
                    'code' => 'CHF',
                    'symbol' => 'CHF',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Chilean Peso',
                    'code' => 'CLP',
                    'symbol' => '$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Chinese Yuan',
                    'code' => 'CNY',
                    'symbol' => '¥',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Colombian Peso',
                    'code' => 'COP',
                    'symbol' => '$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Costa Rican Colón',
                    'code' => 'CRC',
                    'symbol' => '₡',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Cuban Convertible Peso',
                    'code' => 'CUC',
                    'symbol' => '$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Cuban Peso',
                    'code' => 'CUP',
                    'symbol' => '$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Cape Verdean Escudo',
                    'code' => 'CVE',
                    'symbol' => 'Esc',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Czech Koruna',
                    'code' => 'CZK',
                    'symbol' => 'Kč',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Djiboutian Franc',
                    'code' => 'DJF',
                    'symbol' => 'Fdj',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Danish Krone',
                    'code' => 'DKK',
                    'symbol' => 'kr',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Dominican Peso',
                    'code' => 'DOP',
                    'symbol' => 'RD$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Algerian Dinar',
                    'code' => 'DZD',
                    'symbol' => 'دج',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Egyptian Pound',
                    'code' => 'EGP',
                    'symbol' => '£',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Eritrean Nakfa',
                    'code' => 'ERN',
                    'symbol' => 'Nfk',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Ethiopian Birr',
                    'code' => 'ETB',
                    'symbol' => 'Br',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Euro',
                    'code' => 'EUR',
                    'symbol' => '€',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Fijian Dollar',
                    'code' => 'FJD',
                    'symbol' => 'FJ$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Falkland Islands Pound',
                    'code' => 'FKP',
                    'symbol' => '£',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'British Pound Sterling',
                    'code' => 'GBP',
                    'symbol' => '£',
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Georgian Lari',
                    'code' => 'GEL',
                    'symbol' => '₾',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Ghanaian Cedi',
                    'code' => 'GHS',
                    'symbol' => 'GH₵',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Gibraltar Pound',
                    'code' => 'GIP',
                    'symbol' => '£',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Gambian Dalasi',
                    'code' => 'GMD',
                    'symbol' => 'D',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Guinean Franc',
                    'code' => 'GNF',
                    'symbol' => 'FG',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Guatemalan Quetzal',
                    'code' => 'GTQ',
                    'symbol' => 'Q',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Guyanaese Dollar',
                    'code' => 'GYD',
                    'symbol' => 'GY$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Hong Kong Dollar',
                    'code' => 'HKD',
                    'symbol' => 'HK$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Honduran Lempira',
                    'code' => 'HNL',
                    'symbol' => 'L',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Croatian Kuna',
                    'code' => 'HRK',
                    'symbol' => 'kn',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Haitian Gourde',
                    'code' => 'HTG',
                    'symbol' => 'G',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Hungarian Forint',
                    'code' => 'HUF',
                    'symbol' => 'Ft',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Indonesian Rupiah',
                    'code' => 'IDR',
                    'symbol' => 'Rp',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Israeli New Shekel',
                    'code' => 'ILS',
                    'symbol' => '₪',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Indian Rupee',
                    'code' => 'INR',
                    'symbol' => '₹',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Iraqi Dinar',
                    'code' => 'IQD',
                    'symbol' => 'ع.د',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Iranian Rial',
                    'code' => 'IRR',
                    'symbol' => '﷼',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Icelandic Króna',
                    'code' => 'ISK',
                    'symbol' => 'kr',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Jamaican Dollar',
                    'code' => 'JMD',
                    'symbol' => 'J$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Jordanian Dinar',
                    'code' => 'JOD',
                    'symbol' => 'د.ا',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Japanese Yen',
                    'code' => 'JPY',
                    'symbol' => '¥',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Kenyan Shilling',
                    'code' => 'KES',
                    'symbol' => 'KSh',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Kyrgyzstani Som',
                    'code' => 'KGS',
                    'symbol' => 'лв',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Cambodian Riel',
                    'code' => 'KHR',
                    'symbol' => '៛',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Comorian Franc',
                    'code' => 'KMF',
                    'symbol' => 'CF',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'North Korean Won',
                    'code' => 'KPW',
                    'symbol' => '₩',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'South Korean Won',
                    'code' => 'KRW',
                    'symbol' => '₩',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Kuwaiti Dinar',
                    'code' => 'KWD',
                    'symbol' => 'د.ك',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Cayman Islands Dollar',
                    'code' => 'KYD',
                    'symbol' => 'CI$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Kazakhstani Tenge',
                    'code' => 'KZT',
                    'symbol' => '₸',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Lao Kip',
                    'code' => 'LAK',
                    'symbol' => '₭',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Lebanese Pound',
                    'code' => 'LBP',
                    'symbol' => 'ل.ل',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sri Lankan Rupee',
                    'code' => 'LKR',
                    'symbol' => 'Rs',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Liberian Dollar',
                    'code' => 'LRD',
                    'symbol' => 'L$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Lesotho Loti',
                    'code' => 'LSL',
                    'symbol' => 'L',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Libyan Dinar',
                    'code' => 'LYD',
                    'symbol' => 'ل.د',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Moroccan Dirham',
                    'code' => 'MAD',
                    'symbol' => 'د.م.',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Moldovan Leu',
                    'code' => 'MDL',
                    'symbol' => 'L',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Malagasy Ariary',
                    'code' => 'MGA',
                    'symbol' => 'Ar',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Macedonian Denar',
                    'code' => 'MKD',
                    'symbol' => 'ден',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Myanmar Kyat',
                    'code' => 'MMK',
                    'symbol' => 'K',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Mongolian Tögrög',
                    'code' => 'MNT',
                    'symbol' => '₮',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Macanese Pataca',
                    'code' => 'MOP',
                    'symbol' => 'MOP$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Mauritanian Ouguiya',
                    'code' => 'MRU',
                    'symbol' => 'UM',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Mauritian Rupee',
                    'code' => 'MUR',
                    'symbol' => '₨',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Maldivian Rufiyaa',
                    'code' => 'MVR',
                    'symbol' => 'Rf',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Malawian Kwacha',
                    'code' => 'MWK',
                    'symbol' => 'MK',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Mexican Peso',
                    'code' => 'MXN',
                    'symbol' => '$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Malaysian Ringgit',
                    'code' => 'MYR',
                    'symbol' => 'RM',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Mozambican Metical',
                    'code' => 'MZN',
                    'symbol' => 'MT',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Namibian Dollar',
                    'code' => 'NAD',
                    'symbol' => 'N$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Nigerian Naira',
                    'code' => 'NGN',
                    'symbol' => '₦',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Nicaraguan Córdoba',
                    'code' => 'NIO',
                    'symbol' => 'C$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Norwegian Krone',
                    'code' => 'NOK',
                    'symbol' => 'kr',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Nepalese Rupee',
                    'code' => 'NPR',
                    'symbol' => '₨',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'New Zealand Dollar',
                    'code' => 'NZD',
                    'symbol' => 'NZ$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Omani Rial',
                    'code' => 'OMR',
                    'symbol' => 'ر.ع.',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Panamanian Balboa',
                    'code' => 'PAB',
                    'symbol' => 'B/.',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Peruvian Sol',
                    'code' => 'PEN',
                    'symbol' => 'S/',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Papua New Guinean Kina',
                    'code' => 'PGK',
                    'symbol' => 'K',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Philippine Peso',
                    'code' => 'PHP',
                    'symbol' => '₱',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Pakistani Rupee',
                    'code' => 'PKR',
                    'symbol' => '₨',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Polish Złoty',
                    'code' => 'PLN',
                    'symbol' => 'zł',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Paraguayan Guaraní',
                    'code' => 'PYG',
                    'symbol' => '₲',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Qatari Riyal',
                    'code' => 'QAR',
                    'symbol' => 'ر.ق',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Romanian Leu',
                    'code' => 'RON',
                    'symbol' => 'lei',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Serbian Dinar',
                    'code' => 'RSD',
                    'symbol' => 'дин.',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Russian Ruble',
                    'code' => 'RUB',
                    'symbol' => '₽',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Rwandan Franc',
                    'code' => 'RWF',
                    'symbol' => 'FRw',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Saudi Riyal',
                    'code' => 'SAR',
                    'symbol' => 'ر.س',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Solomon Islands Dollar',
                    'code' => 'SBD',
                    'symbol' => 'SI$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Seychellois Rupee',
                    'code' => 'SCR',
                    'symbol' => '₨',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sudanese Pound',
                    'code' => 'SDG',
                    'symbol' => 'ج.س.',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Swedish Krona',
                    'code' => 'SEK',
                    'symbol' => 'kr',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Singapore Dollar',
                    'code' => 'SGD',
                    'symbol' => 'S$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Saint Helena Pound',
                    'code' => 'SHP',
                    'symbol' => '£',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sierra Leonean Leone',
                    'code' => 'SLL',
                    'symbol' => 'Le',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Somali Shilling',
                    'code' => 'SOS',
                    'symbol' => 'Sh',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Surinamese Dollar',
                    'code' => 'SRD',
                    'symbol' => '$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'South Sudanese Pound',
                    'code' => 'SSP',
                    'symbol' => '£',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'São Tomé and Príncipe Dobra',
                    'code' => 'STN',
                    'symbol' => 'Db',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Salvadoran Colón',
                    'code' => 'SVC',
                    'symbol' => '₡',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Syrian Pound',
                    'code' => 'SYP',
                    'symbol' => '£',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Swazi Lilangeni',
                    'code' => 'SZL',
                    'symbol' => 'E',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Thai Baht',
                    'code' => 'THB',
                    'symbol' => '฿',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Tajikistani Somoni',
                    'code' => 'TJS',
                    'symbol' => 'ЅМ',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Turkmenistani Manat',
                    'code' => 'TMT',
                    'symbol' => 'T',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Tunisian Dinar',
                    'code' => 'TND',
                    'symbol' => 'د.ت',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Tongan Paʻanga',
                    'code' => 'TOP',
                    'symbol' => 'T$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Turkish Lira',
                    'code' => 'TRY',
                    'symbol' => '₺',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Trinidad and Tobago Dollar',
                    'code' => 'TTD',
                    'symbol' => 'TT$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'New Taiwan Dollar',
                    'code' => 'TWD',
                    'symbol' => 'NT$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Tanzanian Shilling',
                    'code' => 'TZS',
                    'symbol' => 'TSh',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Ukrainian Hryvnia',
                    'code' => 'UAH',
                    'symbol' => '₴',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Ugandan Shilling',
                    'code' => 'UGX',
                    'symbol' => 'USh',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'United States Dollar',
                    'code' => 'USD',
                    'symbol' => '$',
                    'is_active' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Uruguayan Peso',
                    'code' => 'UYU',
                    'symbol' => '$U',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Uzbekistani Som',
                    'code' => 'UZS',
                    'symbol' => 'лв',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Venezuelan Bolívar Soberano',
                    'code' => 'VES',
                    'symbol' => 'Bs.S.',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Vietnamese Đồng',
                    'code' => 'VND',
                    'symbol' => '₫',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Vanuatu Vatu',
                    'code' => 'VUV',
                    'symbol' => 'VT',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Samoan Tala',
                    'code' => 'WST',
                    'symbol' => 'WS$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'CFA Franc BEAC',
                    'code' => 'XAF',
                    'symbol' => 'FCFA',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'East Caribbean Dollar',
                    'code' => 'XCD',
                    'symbol' => '$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'CFA Franc BCEAO',
                    'code' => 'XOF',
                    'symbol' => 'CFA',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'CFP Franc',
                    'code' => 'XPF',
                    'symbol' => '₣',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Yemeni Rial',
                    'code' => 'YER',
                    'symbol' => '﷼',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Zambian Kwacha',
                    'code' => 'ZMW',
                    'symbol' => 'ZK',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Zimbabwean Dollar',
                    'code' => 'ZWL',
                    'symbol' => 'Z$',
                    'is_active' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ];
            if(Currency::count() == 0)
            {
                Currency::insert($currencies);
            }
        }
        catch(Exception $e)
        {
            DB::rollBack();
            echo $e->getMessage();
        }
        DB::commit();


    }
}
